---
- name:         Get list of services.
  register:     openstack_services
  changed_when: no
  command:      openstack service list -f value -c Type

- name:    Create Image service.
  command: openstack service create --name glance --description "OpenStack Image" image
  when:    '"image" not in openstack_services.stdout'
