---
- name: Configure DB access.
  ini_file:
    dest:    '{{ path }}'
    section: database
    option:  connection
    value:   'mysql+pymysql://glance:{{ mysql_password }}@{{ mysql_host }}/glance'

- name: Use Keystone.
  ini_file:
    dest:    '{{ path }}'
    section: paste_deploy
    option:  flavor
    value:   keystone

- name: Configure Keystone access.
  ini_file:
    dest:    '{{ path }}'
    section: keystone_authtoken
    option:  '{{ item.key }}'
    value:   '{{ item.value }}'
  with_dict:
    auth_uri:            'http://{{ keystone_host }}:5000'
    auth_url:            'http://{{ keystone_host }}:35357'
    memcached_servers:   '{{ keystone_host }}:11211'
    auth_type:           password
    project_domain_name: default
    user_domain_name:    default
    project_name:        service
    username:            glance
    password:            '{{ keystone_password }}'
